### ISSUE TITLE
Pokedex sort by frequency incorrect order

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#282]
![Image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/d9c41ee9-6f1c-4dc0-a7ed-58453a8c7311)

**Comment by benginerd** [comment]
Some notes:

In `\ui\pokedex\index\linkDetail.tsx`, `getPokemonSorter()` determines the order of listed results. For frequency filtering, it is using a Pokemon's base frequency stat, not its calculated frequency. `getPokemonProducingRate()` calculates a Pokemon's frequency based on multiple values, and this is the value that is displayed. This is why Raichu, Gengar, and Jolteon are next to each other but out of order; they all have the same base frequency, and their calculated frequency values are not being compared for sorting. 

In In `\ui\pokedex\index\client.tsx`, `PokedexClient` generates every possible Pokemon ingredient productions. Individual Pokemon have a maximum of 6 possible ingredient combinations, which is why when the Pokedex level filter is set to 60, there will be up to 6 Pokemon of each kind, as all of these are within the `data` variable.

**Comment by benginerd** [comment]
.

**Comment by benginerd** [comment]
Some notes:

In `\ui\pokedex\index\linkDetail.tsx`, `getPokemonSorter()` determines the order of listed results. For frequency filtering, it is using a Pokemon's base frequency stat, not its calculated frequency. `getPokemonProducingRate()` calculates a Pokemon's frequency based on multiple values, and this is the value that is displayed. This is why Raichu, Gengar, and Jolteon are next to each other but out of order; they all have the same base frequency, and their calculated frequency values are not being compared for sorting.

In `\ui\pokedex\index\client.tsx`, `PokedexClient` generates every possible Pokemon ingredient productions. Individual Pokemon have a maximum of 6 possible ingredient combinations, which is why when the Pokedex level filter is set to 60, there will be up to 6 Pokemon of each kind, as all of these are within the data variable.

**Comment by RaenonX** [comment]
For the 1st one, just call `getPokemonProducingRate()` to get the equivalent frequency and sort it from there then.

For the 2nd one, yeah that's expected.

Nice to see you now know how it works, also this was my guess about why it went off as well lol
